formatter: "markdown"

header-from: ./.config/header.md
footer-from: ./.config/footer.md

output:
  file: ./README.md
  mode: replace
  template: |-
    {{ .Content }}

sections:
  hide:
    - modules

content: |-
  {{ .Header }}

  # AWS KMS CMK Terraform module
  A Terraform module which helps you create AWS KMS Customer managed keys. Read [this](https://docs.aws.amazon.com/kms/latest/developerguide/create-keys.html) page for more information, and for a secure reference architecture by AWS, read [this](https://docs.aws.amazon.com/prescriptive-guidance/latest/security-reference-architecture/welcome.html) page.

  ## Example
  ```hcl
  {{ include "./example/main.tf" }}
  ```

  {{ .Requirements }}

  {{ .Providers }}

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  {{ .Footer }}
